# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CypherPlaygroundGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from Info import Info


class UiForm(object):
    def __init__(self, form):
        self.info = Info()
        """Establish self variables and ratios"""
        # Forming initial ratios
        self.width_ratio = 1
        self.height_ratio = 1
        # Establishing base widgets
        self.comboBox = QtWidgets.QComboBox(form)
        self.plainTextEdit_1 = QtWidgets.QPlainTextEdit(form)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(form)
        self.listBox = QtWidgets.QListWidget(form)
        self.lineEdit_1 = QtWidgets.QLineEdit(form)
        self.lineEdit_2 = QtWidgets.QLineEdit(form)
        self.checkbox_1 = QtWidgets.QCheckBox(form)
        self.checkbox_2 = QtWidgets.QCheckBox(form)

    def ratio_alter(self, x, y, width, height):
        """Return coordinates and dimensions altered by the form size"""
        alter_x = self.width_ratio * x
        alter_y = self.height_ratio * y
        alter_width = self.width_ratio * width
        alter_height = self.height_ratio * height
        return QtCore.QRect(alter_x, alter_y, alter_width, alter_height)

    def setup_ui(self, form):
        """Establish GUI components, specialities and connections"""
        def setup_widget(self_name, geometry, name):
            """Call functions based on self_name, geometry and name"""
            self_name.setGeometry(geometry)
            self_name.setObjectName(name)
        # Creating the form
        form.setObjectName("Form")
        form.resize(1000, 750)
        # Altering the ratios
        self.width_ratio = form.width() / 565
        self.height_ratio = form.height() / 399
        # Creating the widgets
        setup_widget(self.comboBox, self.ratio_alter(20, 10, 131, 14), 'comboBox')
        setup_widget(self.listBox, self.ratio_alter(20, 34, 131, 340), 'listBox')
        setup_widget(self.lineEdit_1, self.ratio_alter(169, 10, 75, 14), 'lineEdit_1')
        setup_widget(self.lineEdit_2, self.ratio_alter(466, 10, 75, 14), 'lineEdit_2')
        setup_widget(self.checkbox_1, self.ratio_alter(169, 27, 75, 14), 'checkbox_1')
        setup_widget(self.checkbox_2, self.ratio_alter(466, 27, 75, 14), 'checkbox_2')
        setup_widget(self.plainTextEdit_1, self.ratio_alter(169, 44, 372, 230), 'plainTextEdit_1')
        setup_widget(self.plainTextEdit_2, self.ratio_alter(169, 284, 372, 90), 'plainTextEdit_2')
        # Adding text to lists
        for i in range(len(self.info.jumpers)):
            self.comboBox.addItem(self.info.jumpers[i])
        for i in range(len(self.info.jumps)):
            self.listBox.addItem(self.info.jumps[i])
        self.listBox.clicked.connect(self.clicked)


    def clicked(self):
        item = self.listBox.currentItem()


